<?php
// Language translations
$lang = [
    'en' => [
        'Welcome' => 'Welcome',
        'homepage' => 'Home page',
        'products' => 'Products',
        'title' => 'KG Kitchenware',
        'profile' => 'Profile',
        'review_title' => 'Title',
        'subtitle' => 'Innovative Kitchen Tools',
        'description' => 'We bring practicality and style to your kitchen! KG Kitchenware offers high-quality kitchen gadgets that make everyday life smoother and cooking more enjoyable.',
        'login' => 'Log in',
        'logout' => 'Log out',
        'register' => 'Register',
        'latest_products' => 'Latest Products',
        'no_products' => 'No new products available at the moment.',
        'price' => 'Price',
        'product_image' => 'Product Image',
        'quantity' => 'Quantity',
        'add_to_cart' => 'Add to cart',
        'give_review' => 'Give a Review',
        'read_reviews' => 'Read Reviews',
        'latest_reviews' => 'Latest Reviews',
        'review' => 'Review',
        'stars' => 'Stars',
        'publish_date' => 'Publish Date ',
        'no_reviews' => 'No reviews available at the moment.',
        'leaveReview' => 'Leave a review.',
        'allKategories' => 'All kategories.',
        'WelcomeProducts' => 'Welcome to Kitchen Gadget product page! Check out products and purchase!',
        'Search' => 'Search',
        'SearchProduct' => 'Search for a product',
        'Stock' => 'In stock',
        'emptystock' => 'Empty stock, we will fill it as fast as possble!',
        'noAccount' => 'No account?',
        'YesAccount' => 'Do you already have an account?',
        'PressHere' => 'Press here',
        'ToCreate' => ',To create an account!',
        'Login' => 'Login',
        'Password' => 'Password',
        'CheckPassword' => 'Confirm Password',
        'LogIn' => 'Login',
        'FirstName' => 'First name',
        'LastName' => 'Last name',
        'Email' => 'Email',
        'User' => 'Username',
        'Address' => 'Address',
        'PhoneNmb' => 'Phone number',
        'ChooseProductS' => 'Choose product from menu',
        'ChooseProduct' => '-- Choose product --',
        'Comment' => 'Comment',
        'SavedReview' => 'Your review has been saved!',
        'review_success' => 'Review saved successfully! Thank you for your feedback!',
        'review_error' => 'Error saving review: ',
        'db_query_error' => 'Database query error: ',
        'AllReviews' => 'All reviews ',
        'FilterStar' => 'Filter reviews according to star rating: ',
        'FilterProduct' => 'Filter according to product',
        'AllProducts' => 'All products',
        'writer' => 'Writer',
        'date' => 'Date',
        'YourInfo' => 'Your Information:',
        'ChangeInfo' => 'Change your information',
        'Orders' => 'Order history',
        'OrderID' => 'Order ID',
        'Total' => 'Total price',
        'Date' => 'Date',
        'NoOrders' => 'No orders',
        'Cart' => 'Cart',
        'CartEmpty' => 'Cart is empty',
        'Remove' => 'Remove',
        'ChangeQuantity' => 'Edit quantity',
        'Pay' => 'Pay',
        'Save' => 'Save changes',
        'Close' => 'Close',
        'CorrectInfo' => 'Are all your info correct? If not you can edit them ',
        'Here' => 'Here',
        'ChoosePayment' => 'Choose payment method',
        'Card' => 'Card',
        'Check' => 'Check',
        'CardNumber' => 'Card number',
        'ExpirationDate' => 'Expiration date',
        'Delivery' => 'Choose delivery method',
        'Deliver' => 'Shipping',
        'Fetch' => 'Fetch from a store',
        'ConfirmOrder' => 'Confirm order',
        'OrderConfirm' => 'Order confimation',
        'AddedToCart' => 'Product added to cart!',
        'BeforeCart' => 'Before adding to cart, log in.',
        'NotEnoughProducts' => 'There is not enough products in stock',
        'QuantityCanNotBe' => 'Quantity can not be zero or negative.',
        'OrderConfirmed' => 'Your Order has been confirmed!',
        'ThanksForOrdering' => 'Thank you for ordering from our store!',
        'BackToHomepage' => 'Back to Homepage',
        'SelectLanguage' => 'Select language for your review',
        'FilterLanguage' => 'Filter according to language',

    ],
    'fi' => [
        'Welcome' => 'Tervetuloa',
        'homepage' => 'Etusivu',
        'products' => 'Tuotteet',
        'title' => 'KG Keittiövälineet',
        'profile' => 'Profiili',
        'review_title' => 'Otsikko',
        'subtitle' => 'Innovatiiviset Keittiövälineet',
        'description' => 'Tuomme keittiöösi käytännöllisyyttä ja tyyliä! KG Keittiökalusteet tarjoaa laadukkaita keittiögadgeteja, jotka tekevät arjesta sujuvampaa ja ruoanlaitosta nautinnollisempaa.',
        'login' => 'Kirjaudu sisään',
        'logout' => 'Kirjaudu ulos',
        'register' => 'Rekisteröidy',
        'latest_products' => 'Uusimmat tuotteet',
        'no_products' => 'Ei uusia tuotteita saatavilla tällä hetkellä.',
        'price' => 'Hinta',
        'product_image' => 'Tuotekuva',
        'quantity' => 'Määrä',
        'add_to_cart' => 'Lisää ostoskoriin',
        'give_review' => 'Anna arvostelu',
        'read_reviews' => 'Lue arvosteluja',
        'latest_reviews' => 'Uusimmat arvostelut',
        'review' => 'Arvostelu',
        'stars' => 'Tähtiä',
        'publish_date' => 'Julkaisupäivämäärä ',
        'no_reviews' => 'Ei arvosteluja saatavilla tällä hetkellä.',
        'leaveReview' => 'Jätä arvostelu.',
        'allKategories' => 'Kaikki kategoriat.',
        'WelcomeProducts' => 'Tervetuloa Kitchen Gadget tuote sivulle! Katsaise tuotteita ja osta!',
        'Search' => 'Hae',
        'SearchProduct' => 'Hae tuotteita',
        'Stock' => 'Varastossa',
        'emptystock' => 'Varasto tyhjä, täytämme mahdollisimman pian!',
        'noAccount' => 'Eikö ole vielä tiliä?',
        'YesAccount' => 'Onko sinulla jo tili?',
        'PressHere' => 'Paina tästä',
        'ToCreate' => ', jos haluat luoda tilin!',
        'Login' => 'Käyttäjänimi',
        'Password' => 'Salasana',
        'CheckPassword' => 'Tarkista salasana',
        'LogIn' => 'Kirjaudu',
        'FirstName' => 'Etunimi',
        'LastName' => 'Sukunimi',
        'Email' => 'Sähköposti',
        'User' => 'Käyttäjänimi',
        'Address' => 'Osoite',
        'PhoneNmb' => 'Puhelinnumero',
        'ChooseProductS' => 'Valitse tuote valikosta',
        'ChooseProduct' => '-- Valitse tuote --',
        'Comment' => 'Kommentti',
        'SavedReview' => 'Arvostelusi tallennettu!',
        'review_success' => 'Arvostelu tallennettu onnistuneesti! Kiitos palautteesta!',
        'review_error' => 'Virhe tallentaessa arvostelua: ',
        'db_query_error' => 'Virhe tietokantakyselyssä: ',
        'AllReviews' => 'Kaikki arvostelut ',
        'FilterStar' => 'Suodata arvosteluja tähtiarvostelun mukaan: ',
        'FilterProduct' => 'Suodata tuotteen mukaan: ',
        'AllProducts' => 'Kaikki tuotteet',
        'writer' => 'Kirjoittaja',
        'date' => 'Päivämäärä',
        'YourInfo' => 'Sinun tiedot:',
        'ChangeInfo' => 'Muuta tietojasi',
        'Orders' => 'Tilaus historia',
        'OrderID' => 'Tilauksen ID',
        'Total' => 'Kokonaishinta',
        'Date' => 'Päivämäärä',
        'NoOrders' => 'Ei tilauksia',
        'Cart' => 'Ostoskori',
        'CartEmpty' => 'Ostoskori tyhjä',
        'Remove' => 'Poista',
        'ChangeQuantity' => 'Muuta määrää',
        'Pay' => 'Maksa',
        'Save' => 'Tallenna muutos',
        'Close' => 'Sulje',
        'CorrectInfo' => 'Onko kaikki tietosi oikein? Jos ei ole, voit muokata niitä ',
        'Here' => 'Tästä',
        'ChoosePayment' => 'Valitse maksutapa',
        'Card' => 'Kortti',
        'Check' => 'Lasku',
        'CardNumber' => 'Korttinumero',
        'ExpirationDate' => 'Voimassaoloaika',
        'Delivery' => 'Valitse toimitustapa',
        'Deliver' => 'Postitus',
        'Fetch' => 'Nouto myymälästä',
        'ConfirmOrder' => 'Vahvista tilaus',
        'OrderConfirm' => ' Tilaus vahvistus',
        'AddedToCart' => 'Tuote lisätty ostoskoriin!',
        'BeforeCart' => 'Ennen ostoskoriin lisäämistä, kirjaudu sisään.',
        'NotEnoughProducts' => 'Varastossa ei ole tarpeeksi tuotteita.',
        'QuantityCanNotBe' => 'Määrä ei voi olla nolla tai negatiivinen.',
        'OrderConfirmed' => 'Tilauksesi on vahvistettu!',
        'ThanksForOrdering' => 'Kiitos tilauksestasi. ',
        'BackToHomepage' => ' Takaisin etusivulle',
        'SelectLanguage' => 'Valitse kieli arvostelullesi',
        'FilterLanguage' => 'Suodata kielen mukaan',

    ]
];
$active_language = $_SESSION['lang'] ?? 'fi'; // Default to 'fi' if not set
$current_lang = $lang[$active_language] ?? $lang['fi']; // Fallback to 'fi'

// Function to fetch translations
function t($key)
{
    global $current_lang;
    if (!isset($current_lang[$key])) {
        error_log("Missing translation for key: " . $key);
        return $key;
    }
    return $current_lang[$key];
}
if (isset($_GET['lang']) && array_key_exists($_GET['lang'], $lang)) {
    $_SESSION['lang'] = $_GET['lang'];
    header("Location: " . $_SERVER['PHP_SELF']); // Refresh page
    exit;
}

?>