<?php
// Language translations
$lang = [
    'en' => [
        'Welcome' => 'Welcome',
        'homepage' => 'Home page',
        'products' => 'Products',
        'title' => 'KG Kitchenware',
        'profile' => 'Profile',
        'review_title' => 'Title',
        'subtitle' => 'Innovative Kitchen Tools',
        'description' => 'We bring practicality and style to your kitchen! KG Kitchenware offers high-quality kitchen gadgets that make everyday life smoother and cooking more enjoyable.',
        'login' => 'Log in',
        'logout' => 'Log out',
        'register' => 'Register',
        'latest_products' => 'Latest Products',
        'no_products' => 'No new products available at the moment.',
        'price' => 'Price',
        'product_image' => 'Product Image',
        'quantity' => 'Quantity',
        'add_to_cart' => 'Add to cart',
        'give_review' => 'Give a Review',
        'read_reviews' => 'Read Reviews',
        'latest_reviews' => 'Latest Reviews',
        'review' => 'Review',
        'stars' => 'Stars',
        'publish_date' => 'Publish Date ',
        'no_reviews' => 'No reviews available at the moment.',
        'leaveReview' => 'Leave a review.',
        'allKategories' => 'All Categories',
        'WelcomeProducts' => 'Welcome to Kitchen Gadget product page! Check out products and purchase!',
        'Search' => 'Search',
        'SearchProduct' => 'Search for a product',
        'Stock' => 'In stock',
        'emptystock' => 'Empty stock, we will fill it as fast as possble!',
        'noAccount' => 'No account?',
        'YesAccount' => 'Do you already have an account?',
        'PressHere' => 'Press here',
        'ToCreate' => ',To create an account!',
        'Login' => 'Login',
        'Password' => 'Password',
        'CheckPassword' => 'Confirm Password',
        'LogIn' => 'Login',
        'FirstName' => 'First name',
        'LastName' => 'Last name',
        'FullName' => 'Name',
        'Email' => 'Email',
        'User' => 'Username',
        'Address' => 'Address',
        'PhoneNmb' => 'Phone number',
        'ChooseProductS' => 'Choose product from menu',
        'ChooseProduct' => '-- Choose product --',
        'Comment' => 'Comment',
        'SavedReview' => 'Your review has been saved!',
        'review_success' => 'Review saved successfully! Thank you for your feedback!',
        'review_error' => 'Error saving review: ',
        'db_query_error' => 'Database query error: ',
        'AllReviews' => 'All reviews ',
        'FilterStar' => 'Filter reviews according to star rating: ',
        'FilterProduct' => 'Filter according to product',
        'AllProducts' => 'All products',
        'writer' => 'Writer',
        'date' => 'Date',
        'YourInfo' => 'Your Information:',
        'ChangeInfo' => 'Change your information',
        'Orders' => 'Order history',
        'OrderID' => 'Order ID',
        'Total' => 'Total price',
        'Date' => 'Date',
        'NoOrders' => 'No orders',
        'Cart' => 'Cart',
        'CartEmpty' => 'Cart is empty',
        'Remove' => 'Remove',
        'ChangeQuantity' => 'Edit quantity',
        'Pay' => 'Pay',
        'Save' => 'Save changes',
        'Close' => 'Close',
        'CorrectInfo' => 'Are all your info correct? If not you can edit them ',
        'Here' => 'Here',
        'ChoosePayment' => 'Choose payment method',
        'Card' => 'Card',
        'Check' => 'Check',
        'CardNumber' => 'Card number',
        'ExpirationDate' => 'Expiration date',
        'Delivery' => 'Choose delivery method',
        'Deliver' => 'Shipping',
        'Fetch' => 'Fetch from a store',
        'ConfirmOrder' => 'Confirm order',
        'OrderConfirm' => 'Order confimation',
        'AddedToCart' => 'Product added to cart!',
        'BeforeCart' => 'Before adding to cart, log in.',
        'NotEnoughProducts' => 'There is not enough products in stock',
        'QuantityCanNotBe' => 'Quantity can not be zero or negative.',
        'OrderConfirmed' => 'Your Order has been confirmed!',
        'ThanksForOrdering' => 'Thank you for ordering from our store!',
        'BackToHomepage' => 'Back to Homepage',
        'SelectLanguage' => 'Select language for your review',
        'FilterLanguage' => 'Filter according to language',
        'UserDetails' => 'Your User Details',
        'back' => 'Back to Profile',
        'EditPageInfo' => 'Here you can update your user details.',
        'Save2' => 'Save Changes',
        'pwdchangemsg' => 'Enter a new password:',
        'pwdchange' => 'Change Password',
        'editalert1' => 'Update your details by changing them.',
        'editalert2' => 'Changes saved successfully!',
        'editalert3' => 'Error inserting data.',
        'editalert4' => 'Error with SQL query.',
        'pwdalert1' => 'Password cannot be blank.',
        'pwdalert2' => 'Password successfully changed!',
        'pwdalert3' => 'An error occured while chaning password.',
        'TilauksenID' => 'ID',
        'TotalPrice' => 'Total Price',
        'DMethod' => 'Delivery Method',
        'PMethod' => 'Payment Method',
        'OrderDetails' => 'Order Details',
        'OrderProducts' => 'Products Included in Order',
        'Product' => 'Product',
        'Amount' => 'Amount',
        'PricePerProduct' => 'Price Per Product',
    ],
    //tuotteen kÃ¤Ã¤nÃ¶kset
    'fi' => [
        'Welcome' => 'Tervetuloa',
        'homepage' => 'Etusivu',
        'products' => 'Tuotteet',
        'title' => 'KG KeittiÃ¶vÃ¤lineet',
        'profile' => 'Profiili',
        'review_title' => 'Otsikko',
        'subtitle' => 'Innovatiiviset KeittiÃ¶vÃ¤lineet',
        'description' => 'Tuomme keittiÃ¶Ã¶si kÃ¤ytÃ¤nnÃ¶llisyyttÃ¤ ja tyyliÃ¤! KG KeittiÃ¶kalusteet tarjoaa laadukkaita keittiÃ¶gadgeteja, jotka tekevÃ¤t arjesta sujuvampaa ja ruoanlaitosta nautinnollisempaa.',
        'login' => 'Kirjaudu sisÃ¤Ã¤n',
        'logout' => 'Kirjaudu ulos',
        'register' => 'RekisterÃ¶idy',
        'latest_products' => 'Uusimmat tuotteet',
        'no_products' => 'Ei uusia tuotteita saatavilla tÃ¤llÃ¤ hetkellÃ¤.',
        'price' => 'Hinta',
        'product_image' => 'Tuotekuva',
        'quantity' => 'MÃ¤Ã¤rÃ¤',
        'add_to_cart' => 'LisÃ¤Ã¤ ostoskoriin',
        'give_review' => 'Anna arvostelu',
        'read_reviews' => 'Lue arvosteluja',
        'latest_reviews' => 'Uusimmat arvostelut',
        'review' => 'Arvostelu',
        'stars' => 'TÃ¤htiÃ¤',
        'publish_date' => 'JulkaisupÃ¤ivÃ¤mÃ¤Ã¤rÃ¤ ',
        'no_reviews' => 'Ei arvosteluja saatavilla tÃ¤llÃ¤ hetkellÃ¤.',
        'leaveReview' => 'JÃ¤tÃ¤ arvostelu.',
        'allKategories' => 'Kaikki kategoriat.',
        'WelcomeProducts' => 'Tervetuloa Kitchen Gadget tuote sivulle! Katsaise tuotteita ja osta!',
        'Search' => 'Hae',
        'SearchProduct' => 'Hae tuotteita',
        'Stock' => 'Varastossa',
        'emptystock' => 'Varasto tyhjÃ¤, tÃ¤ytÃ¤mme mahdollisimman pian!',
        'noAccount' => 'EikÃ¶ ole vielÃ¤ tiliÃ¤?',
        'YesAccount' => 'Onko sinulla jo tili?',
        'PressHere' => 'Paina tÃ¤stÃ¤',
        'ToCreate' => ', jos haluat luoda tilin!',
        'Login' => 'KÃ¤yttÃ¤jÃ¤nimi',
        'Password' => 'Salasana',
        'CheckPassword' => 'Tarkista salasana',
        'LogIn' => 'Kirjaudu',
        'FirstName' => 'Etunimi',
        'LastName' => 'Sukunimi',
        'FullName' => 'Nimi',
        'Email' => 'SÃ¤hkÃ¶posti',
        'User' => 'KÃ¤yttÃ¤jÃ¤nimi',
        'Address' => 'Osoite',
        'PhoneNmb' => 'Puhelinnumero',
        'ChooseProductS' => 'Valitse tuote valikosta',
        'ChooseProduct' => '-- Valitse tuote --',
        'Comment' => 'Kommentti',
        'SavedReview' => 'Arvostelusi tallennettu!',
        'review_success' => 'Arvostelu tallennettu onnistuneesti! Kiitos palautteesta!',
        'review_error' => 'Virhe tallentaessa arvostelua: ',
        'db_query_error' => 'Virhe tietokantakyselyssÃ¤: ',
        'AllReviews' => 'Kaikki arvostelut ',
        'FilterStar' => 'Suodata arvosteluja tÃ¤htiarvostelun mukaan: ',
        'FilterProduct' => 'Suodata tuotteen mukaan: ',
        'AllProducts' => 'Kaikki tuotteet',
        'writer' => 'Kirjoittaja',
        'date' => 'PÃ¤ivÃ¤mÃ¤Ã¤rÃ¤',
        'YourInfo' => 'Sinun tiedot:',
        'ChangeInfo' => 'Muuta tietojasi',
        'Orders' => 'Tilaus historia',
        'OrderID' => 'Tilauksen ID',
        'Total' => 'Kokonaishinta',
        'Date' => 'PÃ¤ivÃ¤mÃ¤Ã¤rÃ¤',
        'NoOrders' => 'Ei tilauksia',
        'Cart' => 'Ostoskori',
        'CartEmpty' => 'Ostoskori tyhjÃ¤',
        'Remove' => 'Poista',
        'ChangeQuantity' => 'Muuta mÃ¤Ã¤rÃ¤Ã¤',
        'Pay' => 'Maksa',
        'Save' => 'Tallenna muutos',
        'Close' => 'Sulje',
        'CorrectInfo' => 'Onko kaikki tietosi oikein? Jos ei ole, voit muokata niitÃ¤ ',
        'Here' => 'TÃ¤stÃ¤',
        'ChoosePayment' => 'Valitse maksutapa',
        'Card' => 'Kortti',
        'Check' => 'Lasku',
        'CardNumber' => 'Korttinumero',
        'ExpirationDate' => 'Voimassaoloaika',
        'Delivery' => 'Valitse toimitustapa',
        'Deliver' => 'Postitus',
        'Fetch' => 'Nouto myymÃ¤lÃ¤stÃ¤',
        'ConfirmOrder' => 'Vahvista tilaus',
        'OrderConfirm' => ' Tilaus vahvistus',
        'AddedToCart' => 'Tuote lisÃ¤tty ostoskoriin!',
        'BeforeCart' => 'Ennen ostoskoriin lisÃ¤Ã¤mistÃ¤, kirjaudu sisÃ¤Ã¤n.',
        'NotEnoughProducts' => 'Varastossa ei ole tarpeeksi tuotteita.',
        'QuantityCanNotBe' => 'MÃ¤Ã¤rÃ¤ ei voi olla nolla tai negatiivinen.',
        'OrderConfirmed' => 'Tilauksesi on vahvistettu!',
        'ThanksForOrdering' => 'Kiitos tilauksestasi. ',
        'BackToHomepage' => ' Takaisin etusivulle',
        'SelectLanguage' => 'Valitse kieli arvostelullesi',
        'FilterLanguage' => 'Suodata kielen mukaan',
        'UserDetails' => 'KÃ¤yttÃ¤jÃ¤tietosi',
        'back' => 'Takaisin profiiliin',
        'EditPageInfo' => 'TÃ¤llÃ¤ sivulla voit pÃ¤ivittÃ¤Ã¤ omat kÃ¤yttÃ¤jÃ¤tietosi.',
        'Save2' => 'Tallenna muutokset',
        'pwdchangemsg' => 'SyÃ¶tÃ¤ uusi salasana:',
        'pwdchange' => 'Vaihda salasana',
        'editalert1' => 'PÃ¤ivitÃ¤ tietosi vaihtamalla niitÃ¤.',
        'editalert2' => 'Muutokset tallennettu onnistuneesti!',
        'editalert3' => 'Virhe tiedon syÃ¶tÃ¶ssÃ¤.',
        'editalert4' => 'Virhe SQL lauseessa: ',
        'pwdalert1' => 'Salasana ei saa olla tyhjÃ¤.',
        'pwdalert2' => 'Salasana pÃ¤ivitetty onnistuneesti!',
        'pwdalert3' => 'Virhe salasanan vaihdossa.',
        'TilauksenID' => 'ID',
        'TotalPrice' => 'Kokonaishinta',
        'DMethod' => 'Toimitustapa',
        'PMethod' => 'Maksutapa',
        'OrderDetails' => 'Tilaustiedot',
        'OrderProducts' => 'Tilatut tuotteet',
        'Product' => 'Tuote',
        'Amount' => 'Kpl',
        'PricePerProduct' => 'Hinta per kappale',
    ]
];
$active_language = $_SESSION['lang'] ?? 'fi'; // Oletus on suomi jos ei ole muutoin valittu
$current_lang = $lang[$active_language] ?? $lang['fi'];

// Funktio kielen valitesemiseen
function t($key)
{
    global $current_lang;
    if (!isset($current_lang[$key])) {
        error_log("Missing translation for key: " . $key);
        return $key;
    }
    return $current_lang[$key];
}

// KÃ¤sietellÃ¤Ã¤n kielen vaihto
if (isset($_GET['lang']) && array_key_exists($_GET['lang'], $lang)) {
    $_SESSION['lang'] = $_GET['lang'];

    $current_page = $_GET['page'] ?? 'etusivu';

    // Ohjataan samalle sivulle valitulla kielellÃ¤
    header("Location: " . $_SERVER['PHP_SELF'] . "?page=" . $current_page);
    exit;
}

?>